# Example .mem8/config.yaml
# Project-level configuration for mem8
#
# This file overrides user-level settings (~/.config/mem8/config.yaml)
# and provides project-specific defaults.

# Template source configuration
templates:
  # External template source (overrides builtin)
  # Supports:
  #   - Local paths: /path/to/templates or ./relative/path
  #   - GitHub shorthand: org/repo[@ref][#subdir=path]
  #   - Git URLs: https://github.com/org/repo.git[@ref][#subdir=path]
  #
  # Examples:
  #   default_source: null  # Use builtin templates (default)
  #   default_source: "killerapp/mem8#subdir=mem8/templates"
  #   default_source: "https://github.com/my-org/templates.git@v1.0.0"
  #   default_source: "/path/to/local/templates"
  #
  default_source: null

# Workspace settings
workspace:
  default_template: full  # full, claude-config, or thoughts-repo
  auto_sync: true
  sync_interval: 300  # seconds

# Shared thoughts configuration
shared:
  # Default location for shared thoughts
  # Example: "~/Documents/mem8-Shared" or "/path/to/team/shared"
  default_location: null

# Discovery settings
discovery:
  cross_repo: false  # Enable cross-repository discovery

# Workflow automation
workflow:
  provider: github  # github, gitlab, etc.
  automation_level: standard  # minimal, standard, comprehensive
  github_org: null
  github_repo: null
  auto_detect_repo: true

# Claude Code integration
claude_code:
  integration_enabled: true
  auto_detect_workspace: true
  memory_hierarchy:
    - enterprise
    - project
    - user
    - local

# Sync behavior
sync:
  conflict_resolution: prompt  # prompt, local, shared, newest
  backup_before_sync: true
  exclude_patterns:
    - .git
    - __pycache__
    - "*.pyc"
    - .DS_Store

# Search configuration
search:
  index_enabled: true
  index_content: true
  index_metadata: true
